import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// Styles
import "./globals.css";

// Layouts
import { AppLayout } from "@/layouts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full max-w-[1440px] m-auto">
          <AppLayout>{children}</AppLayout>
        </div>
      </body>
    </html>
  );
}
